version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000-8100:8000-8100"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./dist:/app/dist
      - ./content:/app/content